def get_default_state_config():
    # --- Initialize session state defaults ---
    return {
        "use_mat": True,
        "use_brt": False,
        "use_rf": False,
        "target": "TANN",
        "target_cols": ["TANN", "PANN", "MTWA", "MTCO"],
        "taxa_cols": {},
        "n_neighbors": 5,
        "distance_metric": "squared_chord",
        "brt_trees": 200,
        "brt_learning_rate": 0.05,
        "brt_max_depth": 6,
        "rf_trees": 200,
        "rf_max_depth": 6,
        "cv_folds": 3,
        "random_seed": 42,
        "smoothing_sigma": 2.0,
        "mirror_x": False,
        "prediction_axis": "Age",
        "initialized": False,
        "uploaded_state": None,
        "train_climate_file": None,
        "train_proxy_file": None,
        "test_proxy_file": None,
        "taxa_mask_file": None,
        "coords_file": None,
        "use_dummy": False,
    }
